"use server";

import { createClient } from "@supabase/supabase-js";
import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/session";
import { cleanMultiline, cleanText } from "@/lib/crmValidation";

function sb() { return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!); }
const path = "/yonetim/yayin"; type Result = { error: string|null; id?: string };
export type PublishingInput = { client_id: string; title: string; platform: string; publish_date: string; publish_time?: string|null; caption?: string; hashtags?: string; location?: string; collaboration_account?: string; cover_url?: string; publisher?: string; is_ad?: boolean; publish_url?: string; status?: string };
export type AdvertisingInput = { client_id: string; publishing_job_id?: string|null; title: string; content_url?: string; objective?: string; target_audience?: string; region?: string; budget?: number; start_date?: string|null; end_date?: string|null; owner?: string; ad_account?: string; campaign_name?: string; status?: string; result_notes?: string; report_url?: string };

export async function addPublishingJob(data: PublishingInput): Promise<Result> { try { await requirePermission("publishing.write"); if (!data.client_id || !cleanText(data.title) || !data.publish_date) return { error: "Müşteri, başlık ve yayın tarihi zorunludur." }; const payload = { ...data, title: cleanText(data.title), platform: cleanText(data.platform), caption: cleanMultiline(data.caption), hashtags: cleanText(data.hashtags), location: cleanText(data.location), collaboration_account: cleanText(data.collaboration_account), cover_url: cleanText(data.cover_url), publisher: cleanText(data.publisher), publish_url: cleanText(data.publish_url) }; const { data: row, error } = await sb().from("crm_publishing_jobs").insert(payload).select("id").single(); if (error) return { error: error.message }; revalidatePath(path); return { error: null, id: row.id }; } catch (error) { return { error: String(error) }; } }
export async function updatePublishingStatus(id: string, status: string): Promise<Result> { try { await requirePermission("publishing.write"); const supabase = sb(); const { data: job, error } = await supabase.from("crm_publishing_jobs").update({ status, updated_at: new Date().toISOString() }).eq("id", id).select("*").single(); if (error) return { error: error.message }; if (status === "yayinlandi" && job.is_ad) { const { count } = await supabase.from("crm_advertising_jobs").select("id", { count: "exact", head: true }).eq("publishing_job_id", id); if ((count ?? 0) === 0) await supabase.from("crm_advertising_jobs").insert({ client_id: job.client_id, publishing_job_id: id, title: `${job.title} Reklamı`, content_url: job.publish_url || "", status: "talep_geldi" }); } revalidatePath(path); return { error: null }; } catch (error) { return { error: String(error) }; } }
export async function addAdvertisingJob(data: AdvertisingInput): Promise<Result> { try { await requirePermission("advertising.write"); if (!data.client_id || !cleanText(data.title)) return { error: "Müşteri ve başlık zorunludur." }; const payload = { ...data, title: cleanText(data.title), content_url: cleanText(data.content_url), objective: cleanText(data.objective), target_audience: cleanMultiline(data.target_audience), region: cleanText(data.region), owner: cleanText(data.owner), ad_account: cleanText(data.ad_account), campaign_name: cleanText(data.campaign_name), result_notes: cleanMultiline(data.result_notes), report_url: cleanText(data.report_url) }; const { data: row, error } = await sb().from("crm_advertising_jobs").insert(payload).select("id").single(); if (error) return { error: error.message }; revalidatePath(path); return { error: null, id: row.id }; } catch (error) { return { error: String(error) }; } }
export async function updateAdvertisingStatus(id: string, status: string): Promise<Result> { try { await requirePermission("advertising.write"); const { error } = await sb().from("crm_advertising_jobs").update({ status, updated_at: new Date().toISOString() }).eq("id", id); if (error) return { error: error.message }; revalidatePath(path); return { error: null }; } catch (error) { return { error: String(error) }; } }
