"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { addDesignJob, addEditJob, addRevision, moveJob, toggleRevision, updateJobStatus, type JobKind } from "@/lib/actions/crmProduction";
import { createApprovalRequest } from "@/lib/actions/crmAutomation";

type Client = { id: string; ad: string };
type User = { id: string; username: string; role: string };
type Related = { ad: string } | Array<{ ad: string }> | null;
type Job = { id: string; client_id: string; title: string; priority: "dusuk"|"normal"|"yuksek"|"acil"; queue_position: number; estimated_work_minutes: number; due_date: string|null; created_at: string; status: string; editor?: string; designer?: string; video_type?: string; design_type?: string; drive_url?: string; media_sorting_completed?: boolean; musteriler: Related };
type Revision = { id: string; job_type: JobKind; edit_job_id: string|null; design_job_id: string|null; requested_by: string; reason: string; description: string; assigned_to: string; due_date: string|null; revision_round: number; completed: boolean; created_at: string };
type Tab = "edit" | "design" | "revisions";

const INPUT: React.CSSProperties = { width: "100%", padding: "9px 11px", borderRadius: 8, border: "1px solid var(--c-border)", background: "var(--c-input)", color: "var(--c-text)", fontSize: 13, boxSizing: "border-box" };
const LABEL: React.CSSProperties = { display: "block", fontSize: 10, color: "var(--c-dim)", fontWeight: 700, textTransform: "uppercase", marginBottom: 5 };
const CARD: React.CSSProperties = { background: "var(--c-surface)", border: "1px solid var(--c-border)", borderRadius: 12 };
const EDIT_STATUS = ["cekim_bekliyor","ayiklama_bekliyor","siraya_alinacak","edit_sirasinda","kurgu_basladi","ilk_taslak","koordinator_kontrol","revizede","musteri_onayi","final_hazir","yayina_hazir","yayinlandi"];
const DESIGN_STATUS = ["arastiriliyor","referans_secildi","gorsel_bekliyor","tasarim_sirasinda","ilk_taslak","koordinator_kontrol","revizede","musteri_onayi","final_hazir","yayina_hazir","yayinlandi"];
function relatedName(value: Related) { return Array.isArray(value) ? value[0]?.ad || "Müşteri" : value?.ad || "Müşteri"; }
function waitDays(createdAt: string) { return Math.max(0, Math.floor((Date.now() - new Date(createdAt).getTime()) / 86400000)); }
function urgency(job: Job) { if (job.due_date && new Date(job.due_date) < new Date()) return { label: "Gecikti", color: "#ef4444" }; const days = waitDays(job.created_at); if (days >= 7) return { label: `${days} gün`, color: "#ef4444" }; if (days >= 4) return { label: `${days} gün`, color: "#f59e0b" }; if (days >= 2) return { label: `${days} gün`, color: "#60a5fa" }; return null; }

export function ProductionClient({ clients, users, editJobs, designJobs, revisions }: { clients: Client[]; users: User[]; editJobs: Job[]; designJobs: Job[]; revisions: Revision[] }) {
  const router = useRouter(); const [tab, setTab] = useState<Tab>("edit"); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [approvalLink,setApprovalLink]=useState("");
  const [jobOpen, setJobOpen] = useState(false); const [revisionOpen, setRevisionOpen] = useState(false); const [revisionTarget, setRevisionTarget] = useState<{ kind: JobKind; job: Job }|null>(null);
  const [jobForm, setJobForm] = useState({ client_id: "", title: "", assignee: "", type: "", priority: "normal" as Job["priority"], estimated_work_minutes: "60", due_date: "", drive_url: "", reference_url: "", raw_folder_url: "", selected_media_url: "", media_sorting_completed: false, notes: "" });
  const [revisionForm, setRevisionForm] = useState({ requested_by: "", reason: "", description: "", assigned_to: "", due_date: "" });
  async function run(task: () => Promise<{ error: string|null }>, close?: () => void) { setPending(true); setError(""); const result = await task(); setPending(false); if (result.error) setError(result.error); else { close?.(); router.refresh(); } }
  function openJob() { setJobForm({ client_id: "", title: "", assignee: "", type: tab === "edit" ? "reels" : "post", priority: "normal", estimated_work_minutes: "60", due_date: "", drive_url: "", reference_url: "", raw_folder_url: "", selected_media_url: "", media_sorting_completed: false, notes: "" }); setJobOpen(true); }
  async function submitJob(e: React.FormEvent) { e.preventDefault(); const common = { client_id: jobForm.client_id, title: jobForm.title, priority: jobForm.priority, estimated_work_minutes: Number(jobForm.estimated_work_minutes), due_date: jobForm.due_date || null, drive_url: jobForm.drive_url, reference_url: jobForm.reference_url, queue_position: (tab === "edit" ? editJobs.length : designJobs.length) + 1 }; await run(() => tab === "edit" ? addEditJob({ ...common, editor: jobForm.assignee, video_type: jobForm.type, coordinator_note: jobForm.notes, raw_folder_url: jobForm.raw_folder_url, selected_media_url: jobForm.selected_media_url, media_sorting_completed: jobForm.media_sorting_completed, status: jobForm.media_sorting_completed ? "siraya_alinacak" : "ayiklama_bekliyor" }) : addDesignJob({ ...common, designer: jobForm.assignee, design_type: jobForm.type, copy_text: jobForm.notes, status: "arastiriliyor" }), () => setJobOpen(false)); }
  function openRevision(kind: JobKind, job: Job) { setRevisionTarget({ kind, job }); setRevisionForm({ requested_by: "", reason: "", description: "", assigned_to: kind === "edit" ? job.editor || "" : job.designer || "", due_date: "" }); setRevisionOpen(true); }
  async function submitRevision(e: React.FormEvent) { e.preventDefault(); if (!revisionTarget) return; await run(() => addRevision({ job_type: revisionTarget.kind, job_id: revisionTarget.job.id, ...revisionForm, due_date: revisionForm.due_date || null }), () => setRevisionOpen(false)); }
  async function reorder(kind: JobKind, job: Job, direction: "up"|"down") { const reason = window.prompt("Sıra değişikliği nedeni:"); if (!reason) return; await run(() => moveJob(kind, job.id, direction, reason)); }
  async function requestApproval(kind:JobKind,job:Job){const preview=window.prompt("Müşterinin göreceği önizleme bağlantısı:",job.drive_url||"");if(!preview)return;setPending(true);setError("");const result=await createApprovalRequest({client_id:job.client_id,job_type:kind,job_id:job.id,title:job.title,preview_url:preview});setPending(false);if(result.error)setError(result.error);else if(result.token){setApprovalLink(`${window.location.origin}/onay/${result.token}`);router.refresh()}}
  const activeJobs = tab === "edit" ? editJobs : designJobs;
  const tabs: Array<{ key: Tab; label: string; count: number }> = [{ key: "edit", label: "Editör Sırası", count: editJobs.length }, { key: "design", label: "Tasarımcı Sırası", count: designJobs.length }, { key: "revisions", label: "Revize Merkezi", count: revisions.filter(r => !r.completed).length }];
  return <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
    <div style={{ display: "flex", justifyContent: "space-between" }}><div><h1 style={{ margin: 0, fontSize: 18, color: "var(--c-text)" }}>Üretim Merkezi</h1><p style={{ margin: "4px 0 0", fontSize: 12, color: "var(--c-dim)" }}>Edit, tasarım, kontrol ve revize sıraları.</p></div>{tab !== "revisions" && <button onClick={openJob} style={primary}>+ Yeni İş</button>}</div>
    {error && <div style={{ padding: 10, borderRadius: 8, background: "rgba(248,113,113,.08)", color: "#f87171", fontSize: 12 }}>{error}</div>}{approvalLink&&<div style={{padding:10,borderRadius:8,background:"rgba(16,185,129,.08)",fontSize:12,color:"#34d399"}}>Müşteri onay bağlantısı: <a href={approvalLink} target="_blank" rel="noreferrer" style={{color:"#60a5fa"}}>{approvalLink}</a></div>}
    <div style={{ display: "flex", borderBottom: "1px solid var(--c-border)" }}>{tabs.map(item => <button key={item.key} onClick={() => setTab(item.key)} style={{ background: "transparent", border: "none", borderBottom: tab === item.key ? "2px solid #ec4899" : "2px solid transparent", color: tab === item.key ? "#f472b6" : "var(--c-dim)", padding: "10px 16px", cursor: "pointer", fontWeight: 600 }}>{item.label} ({item.count})</button>)}</div>
    {tab !== "revisions" && <div style={{ ...CARD, overflow: "hidden" }}>{activeJobs.length === 0 ? <Empty text="İş sırası boş." /> : activeJobs.map((job, index) => { const alert = urgency(job); const kind: JobKind = tab; const statuses = kind === "edit" ? EDIT_STATUS : DESIGN_STATUS; return <article key={job.id} style={{ display: "grid", gridTemplateColumns: "54px 1fr 90px 150px 190px", gap: 12, alignItems: "center", padding: "13px 16px", borderBottom: index < activeJobs.length - 1 ? "1px solid var(--c-border)" : "none", borderLeft: `3px solid ${job.priority === "acil" ? "#ef4444" : "transparent"}` }}><div style={{ display: "flex", alignItems: "center", gap: 5 }}><strong style={{ color: "var(--c-text)", fontSize: 15 }}>{index + 1}</strong><div><button onClick={() => reorder(kind, job, "up")} aria-label="Yukarı taşı" style={arrow}>▲</button><button onClick={() => reorder(kind, job, "down")} aria-label="Aşağı taşı" style={arrow}>▼</button></div></div><div><div style={{ fontSize: 13, fontWeight: 700, color: "var(--c-text)" }}>{job.title}</div><div style={{ fontSize: 11, color: "var(--c-dim)", marginTop: 3 }}>{relatedName(job.musteriler)} · {kind === "edit" ? job.editor || "Editör yok" : job.designer || "Tasarımcı yok"} · {job.estimated_work_minutes} dk</div></div><div>{alert && <span style={{ fontSize: 10, color: alert.color, fontWeight: 700 }}>{alert.label}</span>}</div><select value={job.status} onChange={e => run(() => updateJobStatus(kind, job.id, e.target.value))} style={{ ...INPUT, padding: 6 }}>{statuses.map(status => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><div style={{display:"flex",gap:5}}><button onClick={() => openRevision(kind, job)} style={secondary}>Revize</button><button onClick={()=>requestApproval(kind,job)} style={secondary}>Onaya Gönder</button></div></article>; })}</div>}
    {tab === "revisions" && <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(300px,1fr))", gap: 12 }}>{revisions.map(revision => <article key={revision.id} style={{ ...CARD, padding: 16, opacity: revision.completed ? .55 : 1 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ fontSize: 10, color: revision.job_type === "edit" ? "#60a5fa" : "#f472b6", fontWeight: 700, textTransform: "uppercase" }}>{revision.job_type} · {revision.revision_round}. tur</span><input type="checkbox" checked={revision.completed} onChange={e => run(() => toggleRevision(revision.id, e.target.checked))} aria-label="Revize tamamlandı" /></div><h3 style={{ margin: "8px 0 4px", fontSize: 13, color: "var(--c-text)" }}>{revision.reason}</h3><p style={{ margin: 0, fontSize: 12, color: "var(--c-text2)", whiteSpace: "pre-wrap" }}>{revision.description}</p><div style={{ marginTop: 10, fontSize: 10, color: "var(--c-dim)" }}>{revision.requested_by} → {revision.assigned_to || "Atanmadı"}{revision.due_date ? ` · ${revision.due_date}` : ""}</div></article>)}{revisions.length === 0 && <Empty text="Revize kaydı yok." />}</div>}
    {jobOpen && <Modal title={tab === "edit" ? "Edit İşi Ekle" : "Tasarım İşi Ekle"} close={() => setJobOpen(false)}><form onSubmit={submitJob} style={form}><Field label="Müşteri"><select value={jobForm.client_id} onChange={e => setJobForm(f => ({ ...f, client_id: e.target.value }))} style={INPUT} required><option value="">Seçiniz</option>{clients.map(c => <option key={c.id} value={c.id}>{c.ad}</option>)}</select></Field><Field label="İş Başlığı"><input value={jobForm.title} onChange={e => setJobForm(f => ({ ...f, title: e.target.value }))} style={INPUT} required /></Field><div style={grid}><Field label={tab === "edit" ? "Editör" : "Tasarımcı"}><select value={jobForm.assignee} onChange={e => setJobForm(f => ({ ...f, assignee: e.target.value }))} style={INPUT}><option value="">Seçiniz</option>{users.map(u => <option key={u.id} value={u.username}>{u.username}</option>)}</select></Field><Field label="Tür"><input value={jobForm.type} onChange={e => setJobForm(f => ({ ...f, type: e.target.value }))} style={INPUT} /></Field><Field label="Öncelik"><select value={jobForm.priority} onChange={e => setJobForm(f => ({ ...f, priority: e.target.value as Job["priority"] }))} style={INPUT}>{["dusuk","normal","yuksek","acil"].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Tahmini Süre (dk)"><input type="number" min="0" value={jobForm.estimated_work_minutes} onChange={e => setJobForm(f => ({ ...f, estimated_work_minutes: e.target.value }))} style={INPUT} /></Field><Field label="Teslim Tarihi"><input type="date" value={jobForm.due_date} onChange={e => setJobForm(f => ({ ...f, due_date: e.target.value }))} style={INPUT} /></Field><Field label="Drive / Canva"><input type="url" value={jobForm.drive_url} onChange={e => setJobForm(f => ({ ...f, drive_url: e.target.value }))} style={INPUT} /></Field>{tab === "edit" && <><Field label="Ham Dosya Klasörü"><input type="url" value={jobForm.raw_folder_url} onChange={e => setJobForm(f => ({ ...f, raw_folder_url: e.target.value }))} style={INPUT} /></Field><Field label="Ayıklanan Medya Klasörü"><input type="url" value={jobForm.selected_media_url} onChange={e => setJobForm(f => ({ ...f, selected_media_url: e.target.value }))} style={INPUT} /></Field></>}</div>{tab === "edit" && <label style={{ fontSize: 11, color: "var(--c-text2)" }}><input type="checkbox" checked={jobForm.media_sorting_completed} onChange={e => setJobForm(f => ({ ...f, media_sorting_completed: e.target.checked }))} /> Medya ayıklama tamamlandı</label>}<Field label="Koordinatör Notu / Metin"><textarea value={jobForm.notes} onChange={e => setJobForm(f => ({ ...f, notes: e.target.value }))} style={{ ...INPUT, height: 70 }} /></Field><Submit pending={pending} /></form></Modal>}
    {revisionOpen && revisionTarget && <Modal title="Revize Oluştur" close={() => setRevisionOpen(false)}><form onSubmit={submitRevision} style={form}><Field label="İş"><input value={revisionTarget.job.title} style={INPUT} disabled /></Field><div style={grid}><Field label="Revizeyi İsteyen"><input value={revisionForm.requested_by} onChange={e => setRevisionForm(f => ({ ...f, requested_by: e.target.value }))} style={INPUT} required /></Field><Field label="Revizeyi Yapacak"><input value={revisionForm.assigned_to} onChange={e => setRevisionForm(f => ({ ...f, assigned_to: e.target.value }))} style={INPUT} /></Field><Field label="Neden"><input value={revisionForm.reason} onChange={e => setRevisionForm(f => ({ ...f, reason: e.target.value }))} style={INPUT} required /></Field><Field label="Teslim"><input type="date" value={revisionForm.due_date} onChange={e => setRevisionForm(f => ({ ...f, due_date: e.target.value }))} style={INPUT} /></Field></div><Field label="Açıklama"><textarea value={revisionForm.description} onChange={e => setRevisionForm(f => ({ ...f, description: e.target.value }))} style={{ ...INPUT, height: 90 }} required /></Field><Submit pending={pending} /></form></Modal>}
  </div>;
}

const primary: React.CSSProperties = { border: "none", background: "#ec4899", color: "#fff", padding: "8px 14px", borderRadius: 8, cursor: "pointer", fontWeight: 600 };
const secondary: React.CSSProperties = { border: "1px solid rgba(244,114,182,.3)", background: "transparent", color: "#f472b6", padding: "6px 9px", borderRadius: 7, cursor: "pointer", fontSize: 11 };
const arrow: React.CSSProperties = { display: "block", border: "none", background: "transparent", color: "var(--c-dim)", cursor: "pointer", fontSize: 8, padding: 0 };
const form: React.CSSProperties = { display: "flex", flexDirection: "column", gap: 12 }; const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 };
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label style={LABEL}>{label}</label>{children}</div>; }
function Empty({ text }: { text: string }) { return <div style={{ padding: 40, color: "var(--c-dim)", fontSize: 13, textAlign: "center" }}>{text}</div>; }
function Submit({ pending }: { pending: boolean }) { return <button type="submit" disabled={pending} style={{ ...primary, alignSelf: "flex-end" }}>{pending ? "Kaydediliyor..." : "Kaydet"}</button>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div style={{ position: "fixed", inset: 0, zIndex: 160, background: "rgba(0,0,0,.72)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}><div role="dialog" aria-modal="true" aria-label={title} style={{ width: "100%", maxWidth: 620, maxHeight: "92vh", overflowY: "auto", background: "var(--c-surface)", border: "1px solid var(--c-border)", borderRadius: 16, padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><h2 style={{ margin: 0, fontSize: 16, color: "var(--c-text)" }}>{title}</h2><button onClick={close} aria-label="Kapat" style={{ border: "none", background: "transparent", color: "var(--c-dim)", cursor: "pointer" }}>✕</button></div>{children}</div></div>; }
